name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - hydra-core=1.3.2
  - matplotlib=3.4.3
  - pandas=1.3.3
  - pip=24.0
  - scikit-learn=1.0.2
  - jupyterlab=4.2.1
  - pandas-profiling=3.1.0
  - pydantic=1.10.2
  - ipywidgets
  - pip:
      - mlflow==2.13.0
      - wandb==0.17.0
