name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.2
  - pytest=6.2.2
  - scipy=1.13.1
  - pip=24.0
  - pip:
      - mlflow==2.13.0
      - wandb==0.17.0
