name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=24.0
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.13.0
      - wandb==0.17.0
